import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const gothamBlack = localFont({
  src: [
    {
      path: "./fonts/GothamMedium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/GothamBlack.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-gotham",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gothamBlack.variable} ${inter.variable} antialiased`}>
        <div className="bg-alfred-gradient relative w-full">
          <Image
            src="/images/airport_bg.webp"
            alt="Aviones comerciales estacionados en la pista de un aeropuerto durante la noche, con hangares iluminados y torres de luz en el fondo"
            fill
            className="z-1 object-cover opacity-20"
          />
          <div className="bg-alfred-black-blue absolute inset-0"></div>
          <main className="relative z-2 min-h-screen">{children}</main>
        </div>
      </body>
    </html>
  );
}
